### ISSUE TITLE
Link to evaluation dataset

### ISSUE THREAD

**Issue by tomthe** [allenai/S2AND#18]
Thank you for this excellent open AND-algorithm and data!

I followed the link from the paper to this repository, but I was not able to find the S2AND dataset. Could you add some help to the readme, please?

**Comment by sergeyf** [comment]
Hello. In the readme there are instructions to how to download the data:

```
To obtain the training data, run this command after the package is installed (from inside the S2AND directory):
[Expected download size is: 50.4 GiB]

aws s3 sync --no-sign-request s3://ai2-s2-research-public/s2and-release data/
```

Did this not work for you?
