### ISSUE TITLE
Find some wrong labels in dataset?

### ISSUE THREAD

**Issue by hapoyige** [allenai/S2AND#25]
For example, in Pubmed dataset, in "clusters.json" file, There is a cluster “PM_352”： ['18834', '18835', '18836', '18837', '18838', '18839', '18840', '18841']. But I checked from "signatures.json", since '18834' in given_block "z zhang" while '18836' is in given_block "d zhang", how could they be in a same cluster? Is anything I misunderstand?

**Comment by sergeyf** [comment]
Good question! The "given block" came from the original source dataset, but the actual name string we replaced with the name string from inside of Semantic Scholar's database. Sometimes the two sources disagree due to various extraction errors, noise, etc. Just one of the problems with merging lots of multiple datasets but wanting to retain some level of data uniformity.

**Comment by hapoyige** [comment]
Thanks for the reply! Actually, I am using the dataset to do a clustering task so the divided block and cluster labels matter. Here comes another confusion for me, which is, I thought "block" came from original source data and "given_block" is the modified version of S2AND since the number of statistics matches the #Block in TableⅡ in the S2AND paper. Any suggestions?

**Comment by hapoyige** [comment]
I count the "block" field in data but find it does not match any field in TableⅡ. But "given_block" matches #Block (before parentheses), which confuses me.

**Comment by sergeyf** [comment]
You can see here that the "original" block is the "given_block": https://github.com/allenai/S2AND/blob/ce9a5acfaf7e1024143066d2ed6a9fbe02687145/s2and/data.py#L617

Table II has both S2 block sizes and the original ones (in parentheses). Which are you matching to what?

![image](https://user-images.githubusercontent.com/1874668/154883535-8154af14-b758-4ffb-b0bd-bb8bb5701a6c.png)

**Comment by hapoyige** [comment]
For example, In Dataset Arnetminer, I count #unique("given_block")=103, #unique("block")=130. In KISTI,  #unique("given_block")=881, #unique("block")=1044.

**Comment by sergeyf** [comment]
Looks like a bug in how we made the table! Can you please paste the code you are using to count the number of unique blocks? 

@shivashankarrs I believe you generated this table? Do you have the code for its generation?

**Comment by hapoyige** [comment]
Ok, I downloaded the dataset as the README said: 
> aws s3 sync --no-sign-request s3://ai2-s2-research-public/s2and-release data/

and run the code below to count the number of unique blocks:
```
import json
from os.path import join as join
BASE = '/home/ssd2/xdtang/data/S2AND_DATA'

dn_list = ['aminer', 'arnetminer', 'inspire', 'kisti', 'pubmed', 'qian', 'zbmath']
for dn in dn_list:
    print(f'Data: {dn}')
    local_base = join(BASE, dn)
    sigs = json.load(open(join(local_base, f'{dn}_signatures.json')))
    
    # blk->sig->content
    blk2sig_meta = {}
    g_blk2sig_meta = {}
    print('Grouping blocks...')
    for sig, content in sigs.items():
        blk = content['author_info']['block']
        if blk not in blk2sig_meta:
            blk2sig_meta[blk] = {sig: content}
        else:
            blk2sig_meta[blk][sig] = content
        
        g_blk = content['author_info']['given_block']
        if g_blk not in g_blk2sig_meta:
            g_blk2sig_meta[g_blk] = {sig: content}
        else:
            g_blk2sig_meta[g_blk][sig] = content
            
    print(f'{len(blk2sig_meta)} BLOCK found')
    print(f'{len(g_blk2sig_meta)} GIVEN_BLOCK found')
```

**Comment by hapoyige** [comment]
Maybe there are some mistakes in my code or conception of the **BLOCK**  ? I count 2096 BLOCK and 600 GIVEN_BLOCK in dataset Aminer. Does a Block mean a name to disambiguation? I use the data before and think 600 is closer to the Block in the original Aminer dataset.

**Comment by sergeyf** [comment]
Your code is right. The table has errors. I'll put a TODO to update our arxiv file. Thanks for reporting the bug. I don't think this bug affects any of the code correctness. My apologies.

**Comment by sergeyf** [comment]
I checked a few other columns in that table and they look fine. I am going to update the arxiv today.

**Comment by hapoyige** [comment]
Thanks for the correction. Since my concern is the clustering job and dividing blocks is needed. What I would like to know is the "clusters.json" file, is it based on BLOCK or GIVEN_BLOCK? I did not find a document so I checked the matching patterns among signatures, blocks, and cluster labels to guess it, here is my code:

```
import json
import os
from os.path import join as join
from tqdm import tqdm
from collections import OrderedDict
from glob import glob
BASE = '/home/ssd2/xdtang/data/S2AND_DATA'

def mk_if_not_exist(path):
    if not os.path.exists(path):
        os.makedirs(path)

def revert_space(s, syb='-b-'):
    return s.replace(syb, ' ')

def remove_space(s, syb='-b-'):
    return s.replace(' ', syb)

dn_list = ['aminer', 'arnetminer', 'inspire', 'kisti', 'pubmed', 'qian', 'zbmath']
# dn_list = ['aminer']
# divide block sigs
for dn in dn_list:
    print(f'Data: {dn}')
    local_base = join(BASE, dn)
    sigs = json.load(open(join(local_base, f'{dn}_signatures.json')))
    for block_yield in ['block', 'given_block']:
        # blk->sig->content
        blk2sig_meta = {}
        print('Grouping blocks...')
        for sig, content in sigs.items():
            blk = content['author_info'][block_yield]
            if blk not in blk2sig_meta:
                blk2sig_meta[blk] = {sig: content}
            else:
                blk2sig_meta[blk][sig] = content
        print(f'{len(blk2sig_meta)} {block_yield.upper()} found')
        
        print('Saving divided blocks')
        block_sigs_dir = join(local_base, f'{block_yield}_sigs')
        mk_if_not_exist(block_sigs_dir)
        for blk, content in tqdm(blk2sig_meta.items()):
            # avoid space in file name
            blk1 = remove_space(blk)
            with open(join(block_sigs_dir, f'{blk1}.json'), 'w') as f1:
                json.dump(content, f1, indent=2)
        
        block_info_dir = join(local_base, f'{block_yield}_info')
        mk_if_not_exist(block_info_dir)

        block2size = {b: len(v) for b, v in blk2sig_meta.items()}
        block_by_size = OrderedDict(sorted(block2size.items(), key=lambda kv: -kv[1]))
        json.dump(block_by_size, open(join(block_info_dir, 'block_size.json'), 'w'), indent=2)

# save block cluster labels
for dn in dn_list:
    print(f'Data: {dn}')
    local_base = join(BASE, dn)

    all_clu2sigs = json.load(open(join(local_base, f'{dn}_clusters.json')))
    all_clu2sigs = {clu: con['signature_ids'] for clu, con in all_clu2sigs.items()}

    sig2clu = {}
    for clu, sigs in all_clu2sigs.items():
        for sig in sigs:
            if sig in sig2clu:
                print('single sig occur twice?')
            sig2clu[sig] = clu
    for block_yield in ['block', 'given_block']:
        # confirm by block_size
        block_info_dir = join(local_base, f'{block_yield}_info')
        block2size = json.load(open(join(block_info_dir, 'block_size.json')))
        
        all_matched = True
        blk2clu2sigs = {}
        block_dir = join(local_base, f'{block_yield}_sigs')
        block_files = glob(f'{block_dir}/*.json')
        for bf in tqdm(block_files):
            # ignore .json in filename
            blk = bf.split('/')[-1][:-5]
            #         print(f'blk:{blk}')
            exp_blk_size = block2size[revert_space(blk)]

            cur_blk_size = 0
            blk2clu2sigs[blk] = {}
            sigs = json.load(open(bf))
            for sig in sigs.keys():
                cur_clu = sig2clu[sig]
                if cur_clu not in blk2clu2sigs[blk]:
                    blk2clu2sigs[blk][cur_clu] = all_clu2sigs[cur_clu]  # list
                    cur_blk_size += len(all_clu2sigs[cur_clu])
            #         assert cur_blk_size == exp_blk_size
            if cur_blk_size != exp_blk_size:
                print(f'blk {blk} expected size={exp_blk_size}, but found {cur_blk_size}')
                all_matched = False
                break
        if all_matched:
            print(f'{block_yield} matched')
        else:
            print(f'{block_yield} does not matched')
                # pdb.set_trace()
        label_dir = join(local_base, f'{block_yield}_cluster_labels')
        mk_if_not_exist(label_dir)
        for blk, clu2sigs in blk2clu2sigs.items():
            json.dump(clu2sigs, open(join(label_dir, f'{blk}.json'), 'w'), indent=2)
```
After run these codes I find if I use GIVEN_BLOCK, Dataset Aminer, Arnetminer, KISTI and QIAN is perfect matched, but BLOCK does not matched in any of these datasets, which surprise me. I thought you used BLOCK in your paper to get clustering results like TABLE Ⅳ? So why these dismatches and should I use BLOCK or GIVEN_BLOCK if I use S2AND as a benchmark? I'm looking forward to your reply and any suggestions in code or data preprocessing is welcomed!

**Comment by sergeyf** [comment]
What you're encountering is a friction that emerged from trying to balance two factors:

(1) The ground truth clusters come from the original datasets, so we can't modify them. The original datasets use given_blocks.
(2) We want to use uniform metadata - so we used the paper/author data from S2. 

If you combine data from S2 papers/authors AND ground truth clusters from the original data sources, you'll get some noise like what you're seeing. Some signatures that are supposed to be in the same cluster will end up in different blocks. This means that if you're using a standard block then classify strategy these will be impossible to put in the same cluster when it comes time for it.

**Comment by hapoyige** [comment]
Thanks a lot, I think I have known what you mean. Besides, why didn't you generate cluster labels with your new BLOCKS? Through block -> author_ids, because in name disambiguation a unique author_id in a block could naturally be a cluster label, right?

**Comment by sergeyf** [comment]
Perhaps there were other ways to have done it. What's done is done, as they say!

**Comment by shivashankarrs** [comment]
Sorry for the delayed response,

we included the table mainly to show how much data we have and how much is lost when we align to S2 (last two paragraphs of Section III).

So in order to show the number of blocks that got reduced, we considered the count of blocks after aligning to S2 and before (which is the original data from their authors). But to keep this number comparable, the definition of block comes from the original data itself, not S2's block. 

NOTE: We say blocks in S2AND, doesn't mean we use block definition in S2.

The updated table on arxiv (https://arxiv.org/pdf/2103.07534.pdf) says how many blocks are there based on two definitions of blocks (not sure if we should change the caption/related text a bit for this).
