### ISSUE TITLE
Question: Can predictions run in multi-core

### ISSUE THREAD

**Issue by jinamshah** [allenai/S2AND#30]
I see that the current implementation of the prediction using the production model will run on a single-core which is very slow when working with larger datasets.
I was wondering if there is some already explored way of doing this using multiple cores if not a GPU?

**Comment by sergeyf** [comment]
Howdy,

Where do you see that the current implementation will run on a single core?

The clusterer runs in parallel: https://github.com/allenai/S2AND/blob/main/s2and/model.py#L81

The pairwise model does too: https://github.com/allenai/S2AND/blob/main/s2and/model.py#L774

Ditto for the featurizer: https://github.com/allenai/S2AND/blob/main/s2and/featurizer.py#L541

And the paper/author preprocessor: https://github.com/allenai/S2AND/blob/main/s2and/data.py#L192 (although default is currently at n_jobs=1, but you can set this to number of logical cores)

**Comment by jinamshah** [comment]
Hey @sergeyf! 
My observations are purely based on monitoring the core usage using `htop`. I saw the predictor use exactly one core.
Here's my code for reference

```import json
import pickle
from os.path import join
from s2and.data import ANDData
from datetime import datetime

start_time = datetime.now()

with open("production_model.pickle", "rb") as _pkl_file:
	clusterer = pickle.load(_pkl_file)

dataset_name = "<dataset_name>"
parent_dir = "<parent_dir>"
signatures = join(parent_dir, f"{dataset_name}_signatures.json")
papers = join(parent_dir, f"{dataset_name}_papers.json")
paper_embeddings = join(parent_dir, f"{dataset_name}_specter.pickle")
anddata = ANDData(
	signatures=signatures,
	papers=papers,
	specter_embeddings=paper_embeddings,
	name="ablation-test",
	mode="inference",
	block_type="original",
)
pred_clusters, pred_distance_matrices = clusterer['clusterer'].predict(anddata.get_blocks(),
																	   anddata)
with open('temp', 'w') as file:
	file.write(json.dumps(pred_clusters))

print("Total time taken ", datetime.now() - start_time)
```

Let me know if there's something I need to change. Meanwhile, I'll look into changing the n_jobs parameters.

**Comment by sergeyf** [comment]
Here's what we do when we load the `clusterer`:

```
    with open(model_path, "rb") as _pickle_file:
        models = pickle.load(_pickle_file)
    clusterer = models["clusterer"]

    clusterer.n_jobs = n_jobs  # True or False
    clusterer.use_cache = True  # not required
    clusterer.use_default_constraints_as_supervision = use_constraints  # True or False
    clusterer.batch_size = 10000000  # these are for making features
```

**Comment by jinamshah** [comment]
That helps! Thanks!
