### ISSUE TITLE
AttributeError: 'FastCluster' object has no attribute 'input_as_observation_matrix'

### ISSUE THREAD

**Issue by kuldeep7688** [allenai/S2AND#45]
I am trying to run just the inference code on the provided datasets (pubmed, aminer). 

The data loading works fine. But prediction always fails with the weird error.  It happens after the distance matrices made.
The output of the prediction function is given below : 

2024-01-21 20:43:05,794 - s2and - INFO - Running predict on full blocks - no subblocking
2024-01-21 20:43:05,795 - s2and - INFO - Making 130 distance matrices
2024-01-21 20:43:05,795 - s2and - INFO - Initializing pairwise_probas
2024-01-21 20:43:05,797 - s2and - INFO - Pairwise probas initialized with 530735 elements, starting making all pairs
2024-01-21 20:43:05,797 - s2and - INFO - Featurizing batch 0/1
2024-01-21 20:43:07,462 - s2and - INFO - Loading cache...
2024-01-21 20:43:11,738 - s2and - INFO - Cache loaded with 504434 keys
2024-01-21 20:43:11,792 - s2and - INFO - Creating 530735 pieces of work
Creating work: 530735it [00:01, 419772.32it/s]
2024-01-21 20:43:13,061 - s2and - INFO - Created pieces of work
2024-01-21 20:43:13,062 - s2and - INFO - Writing to in memory cache
2024-01-21 20:43:13,063 - s2and - INFO - In memory cache written
2024-01-21 20:43:13,064 - s2and - INFO - Making numpy arrays for features and labels
2024-01-21 20:43:13,516 - s2and - INFO - Numpy arrays made
2024-01-21 20:43:13,517 - s2and - INFO - Making predict flags to separate partial supervision from prediction
2024-01-21 20:43:13,560 - s2and - INFO - Doing pairwise classification
2024-01-21 20:44:07,223 - s2and - INFO - Constructing distance matrices
Writing matrices: 100%|██████████| 530735/530735 [00:00<00:00, 660887.85it/s]
2024-01-21 20:44:08,032 - s2and - INFO - 130 distance matrices made
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 pred_clusters, pred_distance_matrices = clusterer['clusterer'].predict(anddata.get_blocks(), anddata)

File /mnt/gs21/scratch/singhku2/finance_graph_project_data/S2AND/s2and/model.py:660, in Clusterer.predict(self, block_dict, dataset, dists, cluster_model_params, partial_supervision, use_s2_clusters, incremental_dont_use_cluster_seeds, batching_threshold, desired_memory_use)
    658 logger.info("Running predict on full blocks - no subblocking")
    659 start = time.time()
--> 660 pred_clusters, dists = self.predict_helper(
    661     block_dict,
    662     dataset,
    663     dists,
    664     cluster_model_params,
    665     partial_supervision,
    666     use_s2_clusters,
    667     incremental_dont_use_cluster_seeds,
    668 )
    669 end = time.time()
    670 total_predict_time = end - start

File /mnt/gs21/scratch/singhku2/finance_graph_project_data/S2AND/s2and/model.py:738, in Clusterer.predict_helper(self, block_dict, dataset, dists, cluster_model_params, partial_supervision, use_s2_clusters, incremental_dont_use_cluster_seeds)
    736 for block_key in block_dict.keys():
    737     if block_key in dists and len(block_dict[block_key]) > 1:
--> 738         cluster_model = self.set_params(cluster_model_params, clone_flag=True)
    739         with warnings.catch_warnings():
    740             # annoying sparse matrix not sorted warning
    741             warnings.simplefilter("ignore", category=EfficiencyWarning)

File /mnt/gs21/scratch/singhku2/finance_graph_project_data/S2AND/s2and/model.py:455, in Clusterer.set_params(self, params, clone_flag)
    453     params = {k: intify(v) for k, v in params.items()}
    454 if clone_flag:
--> 455     cluster_model = clone(self.cluster_model)
    456     cluster_model.set_params(**params)
    457     return cluster_model

File ~/anaconda3/envs/s2and/lib/python3.8/site-packages/sklearn/base.py:87, in clone(estimator, safe)
     79             raise TypeError(
     80                 "Cannot clone object '%s' (type %s): "
     81                 "it does not seem to be a scikit-learn "
     82                 "estimator as it does not implement a "
     83                 "'get_params' method." % (repr(estimator), type(estimator))
     84             )
     86 klass = estimator.__class__
---> 87 new_object_params = estimator.get_params(deep=False)
     88 for name, param in new_object_params.items():
     89     new_object_params[name] = clone(param, safe=False)

File ~/anaconda3/envs/s2and/lib/python3.8/site-packages/sklearn/base.py:170, in BaseEstimator.get_params(self, deep)
    168 out = dict()
    169 for key in self._get_param_names():
--> 170     value = getattr(self, key)
    171     if deep and hasattr(value, "get_params") and not isinstance(value, type):
    172         deep_items = value.get_params().items()

AttributeError: 'FastCluster' object has no attribute 'input_as_observation_matrix

**Comment by sergeyf** [comment]
What's your scikit learn version? Does it match what's in the requirements?

**Comment by kuldeep7688** [comment]
1.2.2 and yes it does match with the requirements file. 

The code that I am trying to run is : 

`# loading trained model
with open("/mnt/scratch/singhku2/finance_graph_project_data/S2AND/data/production_model.pickle", "rb") as _pkl_file:
    clusterer = pickle.load(_pkl_file)

    
# preparing data 
anddata = ANDData(
    signatures="S2AND/data/pubmed/pubmed_signatures.json",
    papers="S2AND/data/pubmed/pubmed_papers.json",
    specter_embeddings="S2AND/data/pubmed/pubmed_specter.pickle",
    name="pubmed",
    mode="inference",
    block_type="s2",
)`

**Comment by sergeyf** [comment]
This is my fault for the lack of clarity, but the production model needs a specific older branch that's associated with the paper experiments. The main branch is way ahead and the production model for that is not released (yet).

Follow these instructions and let me know if it still doesn't work. 

If it does, I'll fix the readme.

https://github.com/allenai/S2AND#reproducibility

**Comment by kuldeep7688** [comment]
So what I am trying is : 

Setting up a new environment following the instructions in s2and_paper branch 

conda create -y --name s2and python==3.7
conda activate s2and
pip install -r requirements.in
pip install -e .


but after doing this there is mismatch in the numpy installed and numpy used in compiling model.

**Comment by kuldeep7688** [comment]
pip install numpy --upgrade

resolves the issue . working fine now

Thanks for the quick response

**Comment by sergeyf** [comment]
Oh yeah, I see that error sometimes. Weirdly, if you just rerun the code again, it should work anyway...
